input data: country, HDI for year (индекс человеческого развития), gdp_for_year (ввп в год), gdp_per_capita (ввп на душу населения).

output data (m/f - пол группы, соответственно мужской и женский; два числа - это возрастная категория группы):

m_5-14, m_15-24, m_25-34, m_35-54, m_55-74, m_75-, f_5-14, f_15-24, f_25-34, f_35-54, f_55-74, f_75-.

method: простейшая нейронная сеть

data from
https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016

In [2]:
%matplotlib inline  
import numpy as np
from numpy import array as na

import pandas as pd
import random
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

import matplotlib
import matplotlib.pyplot as plt

In [66]:
a=pd.read_csv("data\suicide.csv")

#создаю массив входных столбцов для обучения, состав столбцов очевиден по названию
X_hdi=a["HDI for year"]
X_gdp_p=a["gdp_per_capita ($)"]

# для создания столбцов, отвечающих за страну надо переделать слово в число так, чтобы все числа были равнозначны, для этого
# использую OneHotEncoder, он каждой стране сопоставит вектор, причем все векторы будут равноудалены друг от друга.
c=a["country"]
label_encoder = LabelEncoder()
c = pd.Series(label_encoder.fit_transform(c))
c=c.values.reshape(-1, 1)

onehot_encoder = OneHotEncoder(sparse=False)
matrix = onehot_encoder.fit_transform(c)
X_c = pd.DataFrame(onehot_encoder.fit_transform(c)).T

# объединяю все входные данные в единый массив
X=np.vstack([X_c,X_hdi,X_gdp_p]).T

#удаляю повторяющиеся данные
X=pd.DataFrame(X).drop_duplicates().values
n=len(X)
a['country_num']=c


Дальше я хочу аналогично построить массив ответов. 

In [67]:
b=a.groupby(['country-year','sex','age'])['suicides/100k pop'].mean()
B=pd.DataFrame(b.reset_index(name = "count_num"))
table=pd.pivot_table(B, values=['count_num'], index=['sex','age'],columns=['country-year'] )

Z=list()
for i in B['country-year'].drop_duplicates():
    Z.append(table['count_num'][i].values)

In [69]:
Z

[array([ 4.83,  1.56,  2.15,  0.  ,  0.  ,  2.81,  6.71,  3.28,  5.19,
         0.  ,  0.73,  4.59]),
 array([ 2.71,  1.91,  1.41,  0.  ,  2.03,  5.49,  5.33,  1.79,  4.46,
         0.  ,  2.85,  4.48]),
 array([ 1.67,  0.75,  2.43,  0.  ,  0.67,  0.  ,  3.71,  6.35,  4.71,
         0.  ,  4.22,  8.89]),
 array([ 2.39,  1.5 ,  0.62,  0.  ,  0.61,  0.  ,  3.41,  2.85,  3.49,
         0.  ,  3.13,  0.  ]),
 array([ 3.51,  2.67,  2.11,  0.29,  1.18,  0.  ,  7.4 ,  3.91,  2.85,
         0.27,  4.24,  4.13]),
 array([ 2.12,  1.53,  0.58,  0.  ,  0.57,  5.01,  2.48,  2.59,  2.48,
         0.27,  6.42,  8.13]),
 array([ 4.59,  2.65,  2.24,  0.57,  1.11,  4.9 ,  4.56,  5.58,  3.72,
         1.59,  5.06,  3.98]),
 array([ 5.56,  3.73,  2.49,  0.28,  0.55,  4.85,  6.98,  5.95,  3.16,
         0.53,  1.67,  7.87]),
 array([  7.14,   5.84,   1.89,   1.66,   0.  ,   4.75,  13.5 ,  15.25,
          7.88,   1.05,   6.66,  11.81]),
 array([ 10.83,   3.63,   2.42,   0.27,   3.19,   0.  ,  10.85,  10.82

In [70]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,              nan,   7.96000000e+02],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,              nan,   7.69000000e+02],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,              nan,   8.33000000e+02],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   6.68000000e-01,   1.96400000e+03],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   6.72000000e-01,   2.15000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   6.75000000e-01,   2.30900000e+03]])

In [71]:
a

country  year     sex          age  suicides_no  population  \
0         Albania  1987    male  15-24 years           21      312900   
1         Albania  1987    male  35-54 years           16      308000   
2         Albania  1987  female  15-24 years           14      289700   
3         Albania  1987    male    75+ years            1       21800   
4         Albania  1987    male  25-34 years            9      274300   
5         Albania  1987  female    75+ years            1       35600   
6         Albania  1987  female  35-54 years            6      278800   
7         Albania  1987  female  25-34 years            4      257200   
8         Albania  1987    male  55-74 years            1      137500   
9         Albania  1987  female   5-14 years            0      311000   
10        Albania  1987  female  55-74 years            0      144600   
11        Albania  1987    male   5-14 years            0      338200   
12        Albania  1988  female    75+ years            2       36400   
13        Albania  1988    male  15-24 years           17      319200   
14        Albania  1988    male    75+ years            1       22300   
15        Albania  1988    male  35-54 years           14      314100   
16        Albania  1988    male  55-74 years            4      140200   
17        Albania  1988  female  15-24 years            8      295600   
18        Albania  1988  female  55-74 years            3      147500   
19        Albania  1988  female  25-34 years            5      262400   
20        Albania  1988    male  25-34 years            5      279900   
21        Albania  1988  female  35-54 years            4      284500   
22        Albania  1988  female   5-14 years            0      317200   
23        Albania  1988    male   5-14 years            0      345000   
24        Albania  1989    male    75+ years            2       22500   
25        Albania  1989    male  25-34 years           18      283600   
26        Albania  1989    male  35-54 years           15      318400   
27        Albania  1989    male  55-74 years            6      142100   
28        Albania  1989    male  15-24 years           12      323500   
29        Albania  1989  female  35-54 years            7      288600   
...           ...   ...     ...          ...          ...         ...   
27790  Uzbekistan  2012  female  25-34 years          148     2556673   
27791  Uzbekistan  2012  female  35-54 years           89     3474788   
27792  Uzbekistan  2012    male   5-14 years           67     2701361   
27793  Uzbekistan  2012  female  55-74 years           25     1283060   
27794  Uzbekistan  2012  female    75+ years            4      338557   
27795  Uzbekistan  2012  female   5-14 years           16     2578408   
27796  Uzbekistan  2013    male  35-54 years          481     3346411   
27797  Uzbekistan  2013    male  25-34 years          328     2644648   
27798  Uzbekistan  2013  female  15-24 years          323     3039740   
27799  Uzbekistan  2013    male  15-24 years          320     3171202   
27800  Uzbekistan  2013    male  55-74 years          119     1202790   
27801  Uzbekistan  2013    male    75+ years           13      221002   
27802  Uzbekistan  2013  female  25-34 years          146     2647820   
27803  Uzbekistan  2013  female  35-54 years           99     3547895   
27804  Uzbekistan  2013  female    75+ years            8      345180   
27805  Uzbekistan  2013    male   5-14 years           61     2720938   
27806  Uzbekistan  2013  female  55-74 years           21     1356298   
27807  Uzbekistan  2013  female   5-14 years           31     2595000   
27808  Uzbekistan  2014    male  35-54 years          519     3421300   
27809  Uzbekistan  2014    male  25-34 years          318     2739150   
27810  Uzbekistan  2014  female  15-24 years          347     2992817   
27811  Uzbekistan  2014    male  55-74 years          144     1271111   
27812  Uzbekistan  2014    male  15-24 years          347     312690